// <auto-generated />
using System;
using BusinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(FarmerContext))]
    [Migration("20250816093748_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Farmer", b =>
                {
                    b.Property<Guid>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FarmerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarmerNameEN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FarmerId");

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            FarmerId = new Guid("453d9985-5b77-42f7-91c7-c1ab9022cf4b"),
                            Address = "123 Đường ABC, TP.HCM",
                            FarmerCode = "F001",
                            FarmerName = "Nguyễn Văn A",
                            FarmerNameEN = "Nguyen Van A",
                            InsertDate = new DateTime(2025, 8, 16, 16, 37, 47, 456, DateTimeKind.Local).AddTicks(1469),
                            Phone1 = "0901234567",
                            Phone2 = "0912345678"
                        },
                        new
                        {
                            FarmerId = new Guid("6fecbe2b-e2b0-4825-9984-2e437bff42d0"),
                            Address = "456 Đường XYZ, Hà Nội",
                            FarmerCode = "F002",
                            FarmerName = "Trần Thị B",
                            FarmerNameEN = "Tran Thi B",
                            InsertDate = new DateTime(2025, 8, 16, 16, 37, 47, 456, DateTimeKind.Local).AddTicks(1730),
                            Phone1 = "0987654321",
                            Phone2 = "0976543210"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
